export enum tagTypes {
  videos = "videos",
  promoVideosSlider = "promoVideosSlider",
  promoVideos = "promoVideos",
  categories = "categories",
  relatedVideos = "relatedVideos",
  videoDetails = "videoDetails",
  blogs = "blogs",
  singleBlog = "singleBlog",
  profile = "profile",
  userDashboard = "userDashboard",
  userAnalytics = "userAnalytics",
  getReport = "getReport",
  reportDetails = "reportDetails",
  userVideos = "userVideos",
  sinlgeVideo = "sinlgeVideo",
  states = "states",
  cities = "cities",
  contactus = "contactus",
  allcomment = "allcomment",
  allReplay = "getReplay",
  getlikeVideo = "getlikeVideo",
  watchHistory = "watchHistory",
  channelLanDetails="channelLanDetails",
  // admin start ---------
  getChannels = "getChannels",
  salesRepresentatives = "salesRepresentatives",
  salesRepresentDetails = "salesRepresentDetails",
  getPricings = "getPricings",
  transactionsAdmin = "transactionsAdmin",
  getProBanner = "getProBanner",
  categoriesAdmin = "categoriesAdmin",
  adminSeo = "adminSeo",
  fqaAdmin = "fqaAdmin",
  termsAdmin = "termsAdmin",
  aboutAdmin = "aboutAdmin",
  channelDetailsAdmin = "channeldetailsAdmin",
  overviewAdmin = "overviewAdmin",
  reportAdmin = " reportAdmin",
  reportDetailsAdmin = "reportDetailsAdmin",
  appealAdmin = "appealAdmin",
}

export const tagTypesList = [
  tagTypes.videos,
  tagTypes.promoVideos,
  tagTypes.categories,
  tagTypes.relatedVideos,
  tagTypes.videoDetails,
  tagTypes.blogs,
  tagTypes.singleBlog,
  tagTypes.profile,
  tagTypes.userDashboard,
  tagTypes.userAnalytics,
  tagTypes.getReport,
  tagTypes.reportDetails,
  tagTypes.userVideos,
  tagTypes.sinlgeVideo,
  tagTypes.cities,
  tagTypes.states,
  tagTypes.promoVideosSlider,
  tagTypes.contactus,
  tagTypes.allcomment,
  tagTypes.allReplay,
  tagTypes.getlikeVideo,
  tagTypes.watchHistory,
  tagTypes.getChannels,
  tagTypes.salesRepresentatives,
  tagTypes.salesRepresentDetails,
  tagTypes.getPricings,
  tagTypes.transactionsAdmin,
  tagTypes.getProBanner,
  tagTypes.categoriesAdmin,
  tagTypes.adminSeo,
  tagTypes.fqaAdmin,
  tagTypes.termsAdmin,
  tagTypes.aboutAdmin,
  tagTypes.channelDetailsAdmin,
  tagTypes.overviewAdmin,
  tagTypes.reportAdmin,
  tagTypes.reportDetailsAdmin,
  tagTypes.appealAdmin,
  tagTypes.channelLanDetails
];
