export enum tagTypes {
  videos = "videos",
  promoVideosSlider = "promoVideosSlider",
  promoVideos = "promoVideos",
  categories = "categories",
  relatedVideos = "relatedVideos",
  videoDetails = "videoDetails",
  blogs = "blogs",
  singleBlog = "singleBlog",
  profile = "profile",
  userDashboard = "userDashboard",
  userAnalytics = "userAnalytics",
  getReport = "getReport",
  reportDetails = "reportDetails",
  userVideos = "userVideos",
  sinlgeVideo = "sinlgeVideo",
  states = "states",
  cities = "cities",
  contactus="contactus",
  allcomment="allcomment",
  allReplay="getReplay"
}

export const tagTypesList = [
  tagTypes.videos,
  tagTypes.promoVideos,
  tagTypes.categories,
  tagTypes.relatedVideos,
  tagTypes.videoDetails,
  tagTypes.blogs,
  tagTypes.singleBlog,
  tagTypes.profile,
  tagTypes.userDashboard,
  tagTypes.userAnalytics,
  tagTypes.getReport,
  tagTypes.reportDetails,
  tagTypes.userVideos,
  tagTypes.sinlgeVideo,
  tagTypes.cities,
  tagTypes.states,
  tagTypes.promoVideosSlider,
  tagTypes.contactus,
  tagTypes.allcomment,
  tagTypes.allReplay
];
