import type { Metadata } from "next";
import { Poppins } from "next/font/google"; // Import Poppins
import "@/app/style/globals.css";
import Providers from "@/components/providers";

// Load Poppins font
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // Add desired weights
  display: "swap",
});

export const metadata: Metadata = {
  title: "my tsv",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
