name: Deploy to Production
 
on:
  push:
    branches:
      - main
 
env:
  PROJECT_PATH: "/var/www/usaybek_web"
  PM2_APP_NAME: "usaybek"
 
jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
 
          script: |
            set -e
            echo "Deployment started on server..."
 
            cd ${{ env.PROJECT_PATH }}
 
            # git stash
            git pull
            # git stash pop
 
            npm install
            npm run build
 
            if pm2 list | grep -q "${{ env.PM2_APP_NAME }}"; then
              echo "Restarting existing PM2 process..."
              pm2 restart "${{ env.PM2_APP_NAME }}"
            else
              echo "Starting new PM2 process..."
              pm2 start npm --name "${{ env.PM2_APP_NAME }}" -- start
            fi
 
            pm2 save
 
            echo "Deployment finished successfully."